### 회귀
* 독립변수가 종속변수에 영향을 미치는지 알아보고자 할 때 사용
* 연속형 변수들에 대해 두 변수 사이의 적합도를 측정
* 단순회귀
    - 하나의 종속변수와 하나의 독립변수 사이의 관계 분석
* 다중회귀
    - 하나의 종속변수와 여러 독립변수 사이의 관계 분석

### 회귀 평가지표
* MSE(Mean Squared Error)(평균 제곱 오차)
    - 예측값과 실제값의 차이에 대한 제곱(잔차 제곱)에 대하여 평균을 낸 값
    - 회귀 문제에서 가장 많이 사용하는 성능 지표
    - 모델을 평가하는 평가 지표로 오차를 나타내는 식이므로 수치가 적을 수록 좋은 모델
    - 다른 모델과 비교해야만 성능이 좋은지 알 수 있다.
* RMSE(Root Mean Squared Error)
    - 0에 가까울수록 좋은 모델
    - MSE에 ROOT를 쒸운 값. 즉 MSE의 제곱을 다시 원래 값으로 가져옴(가독성 높임)
* MSE & RMSE
    * 오차에 제곱을 진행했기 때문에 오차가 큰 값은 더 크게 벌어지게 된다. 그럼 결국 좋지 않은 모델로 평가 될수 있다. 즉, 큰오차가 있는지 없는지 판단할 때 사용할 수 있다
* MAE(Mean Absolute Error, 평균 절대 오차)
    - 단순 평균 오차를 보기 때문에 위의 경우와 다르게 오차가 크더라도 전체적으로 안정적인 오차 평균을 구할 수 있다
    - 실제값 대비 예측값의 오차를 나타내는 것으로 값이 낮을 수록 좋다
    - 예측값과 실제값의 차이에 대한 절대값에 대하여 평균을 낸 값
* MAPE(Mean Absolute Percentage Error, 평균 절대 비율 오차)
    - 실제값 대비 예측차이가 얼마나 있는지를 비율(%)로 측정
    - 퍼센트값을 가지며 0에 가까울수록 회귀모형의 성능이 좋다고 해석
* r2(결정계수)
    - 0~1 사이의 값을 표현해 주며 r2의 값이 높을수록 좋다
    - 예측 모델과 실제 모델이 얼마나 강한 상관관계를 가지고 있는지
    - 즉, 데이터 변화에 대해 얼마나 잘 설명되는지를 표현하는 것
    - 예) 실제 데이터 : 1,2,3 -> 예측 데이터 0.8, 1.7, 2.7 -> 실 데이터 흐름과 비슷하게 예측하는 기준(설명이 잘 됨)

* 타겟 데이터
    - 1978년 보스턴 주택 가격
    - 506개 타운의 주택 가격 중앙값(단위 1,000달러)
* 특징 데이터
    - CRIM : 범죄율
    - ZM : 25,000평방 피트 당 주거용 토지의 비율
    - INDUS : 비소매상업지역 면적 비율
    - CHAS : 찰스강의 경계에 위치한 경우는 1, 아니면 0(통로가 하천을 향하면1, 아니면 0)
    - NOX : 일산화질소 농도(천만분의 1)
    - RM : 주택당 방수
    - AGE : 1940년 이전에 건축된 주택의 비율
    - DIS : 5개 주요 고용센터까지의 가중거리
    - RAD : 고속도로 접근성 지수
    - TAX : 재산세율
    - PTRATIO : 학생/교사 비율
    - B ; 인구 중 흑인 거주 비율
    - LSTAT : 인구 중 하위 계층 비율
    - MEDV : 본인 소유의 주택가격(중앙값) (단위: $1,000)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data_set/6.회귀/HousingData.csv")
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,0.00,36.2

In [5]:
y = df['MEDV']
X = df.drop(['MEDV'], axis=1)
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,0.00

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [8]:
X_train.shape, X_test.shape

((354, 13), (152, 13))

In [9]:
from sklearn.neighbors import KNeighborsRegressor

In [10]:
kn = KNeighborsRegressor()
kn.fit(X_train, y_train)

KNeighborsRegressor()

In [11]:
kn.score(X_train, y_train), kn.score(X_test, y_test)

(0.6497845447118866, 0.41580025931226516)

In [14]:
X_test.head(2)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
396,5.87205,0.0,18.10,0.0,0.693,6.405,96.0,1.6768,24,666,20.2,396.90,19.37
92,0.04203,0.0,15.04,0.0,0.464,6.442,53.6,3.6659,4,270,18.2,395.01,8.16

In [13]:
pred = kn.predict(X_test)
pred

array([14.56, 25.58, 11.68, 19.82, 19.78, 26.  , 29.32, 20.6 , 25.24,
       33.34, 40.02, 19.58, 12.12, 20.68, 27.7 , 23.24, 17.38, 29.02,
       16.06, 22.12, 25.58, 26.58, 16.06, 29.32, 20.48, 23.74, 30.38,
       31.16, 22.2 , 21.24, 21.88, 30.66, 17.38, 22.02, 25.36, 17.38,
       24.32, 30.38, 20.48, 17.38, 23.08, 21.64, 19.3 , 24.56, 21.38,
       12.16, 19.9 , 24.66, 18.64, 25.  , 13.18, 27.64, 10.88, 26.76,
        9.74, 29.32, 20.96, 23.6 , 21.38, 17.8 , 21.24, 28.8 , 12.32,
       20.66, 32.78, 13.1 , 22.02, 29.66, 25.44, 29.5 , 23.44, 23.5 ,
       20.48, 29.06, 24.42,  8.88, 23.5 , 22.98, 19.82, 30.38, 23.12,
       21.32, 22.18, 14.5 , 27.22, 17.38, 16.34, 24.1 , 25.92,  9.74,
       27.46, 16.06, 21.38, 29.46, 23.62, 17.38, 12.46, 20.6 , 25.04,
       21.02, 22.34, 40.46, 24.32, 28.64, 30.38, 23.48, 15.58, 10.44,
       29.24, 24.1 , 20.84, 23.3 , 11.86, 25.12, 10.88, 13.96, 23.7 ,
       27.7 , 20.46, 22.22, 12.16, 36.92, 15.38,  8.9 , 19.28, 18.02,
       19.26, 20.48, 11.1 , 30.74, 19.62, 19.72, 20.5 , 25.34, 23.12,
       16.86, 23.02, 29.4 , 24.32, 22.98, 17.06, 22.48, 29.16, 23.5 ,
       15.92, 18.2 , 21.9 , 30.38, 10.86, 21.58, 15.58, 20.08])

In [15]:
from sklearn.metrics import mean_squared_error, r2_score

In [17]:
mse = mean_squared_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))
r2 = r2_score(y_test, pred)

In [18]:
print("mse : ", mse)
print("rmse : ", rmse)
print("r2 : ", r2)

mse :  49.94231315789473
rmse :  7.0669875589175
r2 :  0.41580025931226516

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [20]:
rfr = RandomForestRegressor()
rfr.fit(X_train, y_train)

RandomForestRegressor()

In [21]:
pred = rfr.predict(X_test)
mse = mean_squared_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))
r2 = r2_score(y_test, pred)

print("mse : ", mse)
print("rmse : ", rmse)
print("r2 : ", r2)

print("train : ", rfr.score(X_train, y_train))
print("test : ", rfr.score(X_test, y_test))

mse :  9.754769953947367
rmse :  3.1232627097231775
r2 :  0.8858936697716069
train :  0.9678671279940556
test :  0.8858936697716069