### 사과 품질 분류하기
* 컬럼
    - Size : 크기
    - Weight : 무게
    - Sweetness : 단맛
    - Crunchiness : 아삭한 정도
    - Juiciness : 사과 즙의 정도
    - Ripeness : 사과의 숙성 정도
    - Acidity : 신맛
    - Quality : 품질

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data_set/4.분류/apple_quality.csv")
df.head()

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good

In [3]:
df['Quality'].unique()

array(['good', 'bad', nan], dtype=object)

In [4]:
df.isnull().sum()

A_id           1
Size           1
Weight         1
Sweetness      1
Crunchiness    1
Juiciness      1
Ripeness       1
Acidity        0
Quality        1
dtype: int64

In [5]:
df.shape

(4001, 9)

In [6]:
df.dropna(axis=0, inplace=True)

In [7]:
df.shape

(4000, 9)

In [8]:
df.isnull().sum()

A_id           0
Size           0
Weight         0
Sweetness      0
Crunchiness    0
Juiciness      0
Ripeness       0
Acidity        0
Quality        0
dtype: int64

In [9]:
df.columns

Index(['A_id', 'Size', 'Weight', 'Sweetness', 'Crunchiness', 'Juiciness',
       'Ripeness', 'Acidity', 'Quality'],
      dtype='object')

In [10]:
df.head(1)

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.34633,-1.012009,1.8449,0.32984,-0.491590483,good

In [14]:
features = ['Size', 'Weight', 'Sweetness', 'Crunchiness', 'Juiciness',
       'Ripeness', 'Acidity']
label = 'Quality'
X, y = df[features], df[label]
X.head(3), y

(       Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
 0 -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840
 1 -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530
 2 -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033

         Acidity
 0  -0.491590483
 1  -0.722809367
 2   2.621636473  ,
 0       good
 1       good
 2        bad
 3       good
 4       good
         ...
 3995     bad
 3996    good
 3997     bad
 3998    good
 3999    good
 Name: Quality, Length: 4000, dtype: object)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [17]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((2800, 7), (2800,), (1200, 7), (1200,))

### 모델 생성 및 학습, 평가

#### Kneighbors(K-최근접 이웃 알고리즘)
* 주위의 가장 가까운 다른 데이터를 보고 현재 데이터를 판단
* 기본 비교 개수는 5개로 되어 있다
* 비교 개수를 변경하고자 할 경우 n_neighbors에 값 지정

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
kn = KNeighborsClassifier() #모델생성
kn.fit(X_train, y_train) #학습
kn.score(X_test, y_test)

0.8858333333333334

#### SVM(Support Vector Machine)
* 특정 데이터들을 구분하는 선을 찾고, 이를 기반으로 패턴을 인식하는 방법
* kernel : linear, rbf
* linear : 선형으로 데이터들을 구분지을 수 있는 경우. 즉, 데이터 분포가 균일 적인 경우
* rbf : 선형으로 데이터를 구분지을 수 없는 경우. 즉, 데이터 분포가 복잡한 경우

In [20]:
import sklearn.svm as svm

In [21]:
svm_linear = svm.SVC(kernel='linear')
svm_linear.fit(X_train, y_train)
svm_linear.score(X_test, y_test)

0.7533333333333333

In [22]:
svm_linear = svm.SVC(kernel='rbf')
svm_linear.fit(X_train, y_train)
svm_linear.score(X_test, y_test)

0.8783333333333333

### DecisionTree
* 특정 조건에 따라 가지치기 과정을 반복하면서 모델을 생성한다

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [24]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt.score(X_test, y_test)

0.795

### Ensemble(앙상블)
* 여러 개의 분류기(알고리즘)를 생성하고 그 예측을 결합함으로써 보다 정확한 분류기 생성
* 앙상블의 대표 알고리즘은 랜덤포레스트와 그래디언트부스팅이 있다
>
* 앙상블 학습의 유형
    - 보팅(Voting) : 서로 다른 알고리즘을 가진 분류기를 결합하여 사용
    - 배깅(Bagging) : 모두 같은 유형의 알고리즘을 가진 분류기를 결합하여 사용
        * 대표적 알고리즘인 랜덤포레스트가 있다
    - 부스팅(Boosting) : 오류를 개선해 나가면서 학습하는 방식(다른 알고리즘에 비해 시간이 더 걸림)

#### Voting(보팅)
* 하드보팅(Hard Voting) : 다수의 결정에 의해 결과값이 선정된다
* 소프트보팅(Soft Voting) : 결정된 값들의 평균을 구하고 가장 높은 값을 선정
* 일반적으로 하드보팅보다 소프트 보팅이 성능이 좋아 소프트 보팅을 많이 사용한다

In [27]:
svm_rbf = svm.SVC(kernel="rbf", probability=True)
svm_rbf.fit(X_train, y_train)

kn = KNeighborsClassifier()
kn.fit(X_train, y_train)

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [29]:
from sklearn.ensemble import VotingClassifier

In [30]:
vo = VotingClassifier(estimators=[
    ('svc', svm_rbf), ('knn', kn), ('DT', dt)], voting='soft')

In [31]:
vo.fit(X_train, y_train)
print("vo : ", vo.score(X_test, y_test))
print("svm_rbf : ", svm_rbf.score(X_test, y_test))
print("kn : ", kn.score(X_test, y_test))
print("dt : ", dt.score(X_test, y_test))

vo :  0.8625
svm_rbf :  0.8783333333333333
kn :  0.8858333333333334
dt :  0.7941666666666667

#### RandomForest(랜덤포레스트)
* decision tree 알고리즘을 여러 개의 분류기로 만들어서 보팅(소프트보팅)으로 최종 결정한다

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
rfc.score(X_test, y_test)

0.8716666666666667

#### 부스팅(Boosting)
* GBM(Gradient Boosting Machine)
    - decision tree를 묶어 강력한 model을 만드는 ensemble기법입니다.
    - 순차적으로 학습-예측하면서 잘못 예측한 데이터의 오류를 개선해 나가면서 학습하는 방법
    - 다른 알고리즘에 비해 처리속도가 느림

In [34]:
from sklearn.ensemble import GradientBoostingClassifier

In [35]:
gbc = GradientBoostingClassifier()
gbc.fit(X_train, y_train)
gbc.score(X_test, y_test)

0.8441666666666666

### 예측

In [36]:
X_test.head(3)

,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity
796,0.946640,0.629283,0.662393,1.196955,-0.717912,-1.797072,0.584263593
165,-0.348625,1.836154,-0.191223,3.549382,-0.850151,-3.651885,1.656620737
1418,-0.584733,-1.159163,0.811467,2.244678,0.509463,2.273860,3.091904815

In [37]:
kn.predict(X_test)

array(['bad', 'good', 'good', ..., 'good', 'bad', 'bad'],
      shape=(1200,), dtype=object)

In [38]:
y_test

796     good
165      bad
1418    good
133     good
2271     bad
        ...
2071    good
2498    good
967      bad
488      bad
1605     bad
Name: Quality, Length: 1200, dtype: object

In [42]:
kn.predict([[-0.348625,1.836154,-0.191223,3.549382,-0.850151,-3.651885,1.656620737]])

C:\Users\orudw\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['good'], dtype=object)

In [41]:
X_test.head()

,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity
796,0.946640,0.629283,0.662393,1.196955,-0.717912,-1.797072,0.584263593
165,-0.348625,1.836154,-0.191223,3.549382,-0.850151,-3.651885,1.656620737
1418,-0.584733,-1.159163,0.811467,2.244678,0.509463,2.273860,3.091904815
133,4.420782,-2.547671,-1.756286,0.901810,-0.412841,1.987165,1.613529813
2271,-1.070138,-1.454871,-2.481910,1.203107,1.899228,2.258959,0.893563954